### ISSUE TITLE
Add gitleaks for detecting secrets in CI workflow

### ISSUE THREAD

**Issue by a-thiery** [kaiko-ai/eva#356]
## Objective

To enhance the security of _`eva`_'s repository, we propose integrating [gitleaks](https://github.com/gitleaks/gitleaks) into our Continuous Integration (CI) workflow. Gitleaks will allow us to automatically detect and prevent the inclusion of sensitive information, such as API keys, passwords, and other secrets.

## Tasks

- [x] Integrate gitleaks into the CI workflow. 
- [x] Configure gitleaks settings to suit our project's requirements.
- [x] Test the gitleaks integration works.
